name: Streamsets
description: |
  (Experimental) Streamsets
version: 0.10.2.0-rancher
category: Clustering
maintainer: "Pavithra.KC <Pavithra.KC@intlfcstone.com>"
minimum_rancher_version: 1.6
license: 
projectURL: https://intlfcstone.visualstudio.com/DefaultCollection/INTL%20FCStone%20Markets/_git/Pontoon