.catalog:
    name: "StreamsetsDC"
    version: "2.5-rancher"
    description: " Conquer Dataflow Chaos"
    minimum_rancher_version: 1.6
  sidekick:
    scale: 1
    start_on_create: true
  StreamsetsDC:
    scale: 1
    start_on_create: true
