version: '2'
catalog:
    name: "StreamsetsDC"
    version: "2.5.0.0"
    description: "Conquer Dataflow Chaos"
    minimum_rancher_version: 1.6
    questions:
        - variable: "streamsets_port"
          type: "int"
          required: true
          label: "Streamsets Port:"
          description: "Port to expose for Streamsets"
          default: 18630
services:    
  sidekick:
    scale: 1
    start_on_create: true
  StreamsetsDC:
    scale: 1
    start_on_create: true
